### ISSUE TITLE
Collaboration with PeepethClient to create one app

### ISSUE THREAD

**Issue by danimesq** [ligi/PeepDroid#18]
My suggestion is to merge your two apps https://github.com/matterinc/PeepethClient
to focus on just one mobile client, using Cordova instead of HTML2Swift

**Comment by danimesq** [comment]
@ligi @BaldyAsh
Invite you both to [Peepeth organization](https://github.com/orgs/peepeth/) on GitHub

**Comment by ligi** [comment]
Hey - thanks for the suggestion! But I want peepeth to stay native android and not be cross platform - so I have to close this issue. Might join the github org when it is under control of Bevan.
